### ISSUE TITLE
issue on clean task

### ISSUE THREAD

**Issue by victorsosa** [mohsen1/generator-angular-directive#6]
Hi,
There is an issue with the clean task. it should be like this:
`del(['/dist'], cb);`

The "/" is missing so it will throw an error.

I want to tell you that this is a awesome generator, thank you and keep going on it.
You save me a lot of time.

**Comment by mohsen1** [comment]
Thanks for pointing that out. Could you make a pull request with the fix? Feel free to use a new dependency for this.

**Comment by victorsosa** [comment]
Actually that a took a look into it; the component with the issue is the angular-directive-boilerplate. So I will submit the PR on the angular-directive-boilerplate project.

**Comment by victorsosa** [comment]
PR sent
